export const Orders = [
  {
    id: 1,
    body: "This is some awesome thinking!",
    postId: 100,
    user: { id: 63, username: "eburras1q" },
    timeStamp: "12-1-2020",
    payment: "UPI",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Pending",
    price: 200,
  },
  {
    id: 2,
    body: "What terrific math skills you’re showing!",
    postId: 27,
    user: { id: 71, username: "omarsland1y" },
    timeStamp: "6-5-2021",
    payment: "Cash",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Paid",
    price: 1200,
  },
  {
    id: 3,
    body: "You are an amazing writer!",
    postId: 61,
    user: { id: 29, username: "jissetts" },
    timeStamp: "19-7-2023",
    payment: "Stripe",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Refund",
    price: 700,
  },
  {
    id: 4,
    body: "Wow! You have improved so much!",
    postId: 8,
    user: { id: 19, username: "bleveragei" },
    timeStamp: "21-12-1999",
    payment: "Cash",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Pending",
    price: 400,
  },
  {
    id: 5,
    body: "Nice idea!",
    postId: 62,
    user: { id: 70, username: "cmasurel1x" },
    timeStamp: "1-11-2020",
    payment: "UPI",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Paid",
    price: 1249,
  },
  {
    id: 6,
    body: "You are showing excellent understanding!",
    postId: 19,
    user: { id: 97, username: "cdavydochkin2o" },
    timeStamp: "1-11-2020",
    payment: "Cash",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Paid",
    price: 120,
  },
  {
    id: 7,
    body: "This is clear, concise, and complete!",
    postId: 47,
    user: { id: 22, username: "froachel" },
    timeStamp: "1-11-2020",
    payment: "Cash",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Pending",
    price: 1200,
  },
  {
    id: 8,
    body: "What a powerful argument!",
    postId: 47,
    user: { id: 82, username: "kogilvy29" },
    timeStamp: "1-11-2020",
    payment: "Stripe",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Pending",
    price: 456,
  },
  {
    id: 9,
    body: "I knew you could do it!",
    postId: 64,
    user: { id: 31, username: "smargiottau" },
    timeStamp: "1-11-2020",
    payment: "UPI",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Success",
    price: 3400,
  },
  {
    id: 10,
    body: "Wonderful ideas!",
    postId: 4,
    user: { id: 35, username: "mbrooksbanky" },
    timeStamp: "1-11-2020",
    payment: "UPI",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Success",
    price: 6000,
  },
  {
    id: 11,
    body: "It was a pleasure to grade this!",
    postId: 2,
    user: { id: 68, username: "rstrettle1v" },
    timeStamp: "1-11-2020",
    payment: "Cash",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Refund",
    price: 1000,
  },
  {
    id: 12,
    body: "Keep up the incredible work!",
    postId: 50,
    user: { id: 77, username: "rkingswood24" },
    timeStamp: "1-11-2020",
    payment: "Cash",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Pending",
    price: 1200,
  },
  {
    id: 13,
    body: "My goodness, how impressive!",
    postId: 37,
    user: { id: 28, username: "xisherwoodr" },
    timeStamp: "1-11-2020",
    payment: "Stripe",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Paid",
    price: 1200,
  },
  {
    id: 14,
    body: "You’re showing inventive ideas!",
    postId: 30,
    user: { id: 57, username: "bpickering1k" },
    timeStamp: "1-11-2020",
    payment: "UPI",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Pending",
    price: 1200,
  },
  {
    id: 15,
    body: "You’ve shown so much growth!",
    postId: 44,
    user: { id: 76, username: "cgaber23" },
    timeStamp: "1-11-2020",
    payment: "Cash",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Paid",
    price: 1200,
  },
  {
    id: 16,
    body: "Interesting thoughts!",
    postId: 71,
    user: { id: 100, username: "pcumbes2r" },
    timeStamp: "1-11-2020",
    payment: "UPI",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Pending",
    price: 300,
  },
  {
    id: 17,
    body: "I love your neat work!",
    postId: 68,
    user: { id: 37, username: "nwytchard10" },
    timeStamp: "1-11-2020",
    payment: "Cash",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Pending",
    price: 1200,
  },
  {
    id: 18,
    body: "Doesn’t it feel good to do such great work?",
    postId: 41,
    user: { id: 31, username: "smargiottau" },
    timeStamp: "1-11-2020",
    payment: "Cash",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Pending",
    price: 1200,
  },
  {
    id: 19,
    body: "First-rate work!",
    postId: 75,
    user: { id: 60, username: "dlambarth1n" },
    timeStamp: "1-11-2020",
    payment: "Cash",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Pending",
    price: 1200,
  },
  {
    id: 20,
    body: "This is fascinating information!",
    postId: 48,
    user: { id: 17, username: "vcholdcroftg" },
    timeStamp: "1-11-2020",
    payment: "Cash",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Pending",
    price: 1200,
  },
  {
    id: 21,
    body: "You inspire me!",
    postId: 29,
    user: { id: 5, username: "kmeus4" },
    timeStamp: "1-11-2020",
    payment: "Cash",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Pending",
    price: 1200,
  },
  {
    id: 22,
    body: "This is right on target!",
    postId: 18,
    user: { id: 31, username: "smargiottau" },
    timeStamp: "1-11-2020",
    payment: "Cash",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Pending",
    price: 1200,
  },
  {
    id: 23,
    body: "What an astounding observation!",
    postId: 73,
    user: { id: 14, username: "mturleyd" },
    timeStamp: "1-11-2020",
    payment: "Cash",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Pending",
    price: 1200,
  },
  {
    id: 24,
    body: "This is very well thought out!",
    postId: 32,
    user: { id: 16, username: "dpierrof" },
    timeStamp: "1-11-2020",
    payment: "Cash",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Pending",
    price: 1200,
  },
  {
    id: 25,
    body: "I can tell you’ve been practicing!",
    postId: 44,
    user: { id: 78, username: "dbuist25" },
    timeStamp: "1-11-2020",
    payment: "Cash",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Pending",
    price: 1200,
  },
  {
    id: 26,
    body: "You’ve come a long way!",
    postId: 70,
    user: { id: 82, username: "kogilvy29" },
    timeStamp: "1-11-2020",
    payment: "Cash",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Pending",
    price: 1200,
  },
  {
    id: 27,
    body: "I can tell you’ve been paying attention!",
    postId: 60,
    user: { id: 74, username: "ahinckes21" },
    timeStamp: "1-11-2020",
    payment: "Cash",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Pending",
    price: 1200,
  },
  {
    id: 28,
    body: "Reading this made my day!",
    postId: 85,
    user: { id: 85, username: "kpondjones2c" },
    timeStamp: "1-11-2020",
    payment: "Cash",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Pending",
    price: 1200,
  },
  {
    id: 29,
    body: "This is very perceptive!",
    postId: 13,
    user: { id: 30, username: "kdulyt" },
    timeStamp: "1-11-2020",
    payment: "Cash",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Pending",
    price: 1200,
  },
  {
    id: 30,
    body: "What an accomplishment!",
    postId: 23,
    user: { id: 36, username: "dalmondz" },
    timeStamp: "1-11-2020",
    payment: "Cash",
    email: "rhallawellb@dropbox.com",
    paymentStatus: "Pending",
    price: 1200,
  },
];
